### PR TITLE
Split packages

### PR DESCRIPTION
**Pull request by wilbowma**
Split library, documentation, and tests into separate packages.

### CODE REVIEW

**Comment by stamourv** [comment]
That looks like a good change.
Since you may be the only person actively looking at this code, I've given you write access to the repo.
You're welcome to merge this whenever you want.

**Comment by wilbowma** [comment]
Can you modify the package server to use the `sexp-diff` path, or give me access to that package? https://pkgd.racket-lang.org/pkgn/package/sexp-diff

**Comment by sorawee** [comment]
This commit seems to break other packages that depend on `sexp-diff`. E.g., 

- https://pkg-build.racket-lang.org/server/built/fail/pollen.txt
- https://pkg-build.racket-lang.org/server/built/fail/markdown.txt

**Comment by stamourv** [comment]
I just fixed this on the package server. The problem should go away at the next index refresh.
@wilbowma: I also added you as an author on the package server, which may(?) give you edit access, in case further changes are necessary in the future.

**Comment by samth** [comment]
This does not seem to be fixed on the package server. The paths listed here: https://pkgs.racket-lang.org/package/sexp-diff are still incorrect and error when I try to install them.

**Comment by stamourv** [comment]
Looks like something had gotten garbled. Should be fixed now?

**Pull request merged**
